RED: Before fixing the bug, we first fix the error message.
Specifically, before this commit we got this error message:

    $ time jasmine-node --captureExceptions spec
    ...................Promoting slug a_slug_id to prod.
    >>>>>>>>>> ALL'S WELL
    "Deploying a_slug_id to app b {Promotion of: most_recent_at_a}"
    ....Promoting slug a_slug_id to prod.
    .....F.......

    Failures:

      1) promoter properly fails if could not receive a status of prod. or staging
       Message:
         Expected null to equal 'mostRecentRelease() failed'.
       Stacktrace:
         Error: Expected null to equal 'mostRecentRelease() failed'.
        at /home/imaman/workspace/green-site/spec/promoter.spec.js:113:19
        at /home/imaman/workspace/green-site/acceptance/promoter.js:78:24
        at applyAt (/home/imaman/workspace/green-site/funflow.js:19:16)
        at next (/home/imaman/workspace/green-site/funflow.js:24:22)
        at applyAt (/home/imaman/workspace/green-site/funflow.js:30:21)
        at next (/home/imaman/workspace/green-site/funflow.js:24:22)
        at applyAt (/home/imaman/workspace/green-site/funflow.js:30:21)
        at next (/home/imaman/workspace/green-site/funflow.js:24:22)

      2) promoter properly fails if could not receive a status of prod. or staging
       Message:
         Expected '' to be undefined.
       Stacktrace:
         Error: Expected '' to be undefined.
        at /home/imaman/workspace/green-site/spec/promoter.spec.js:114:20
        at /home/imaman/workspace/green-site/acceptance/promoter.js:78:24
        at applyAt (/home/imaman/workspace/green-site/funflow.js:19:16)
        at next (/home/imaman/workspace/green-site/funflow.js:24:22)
        at applyAt (/home/imaman/workspace/green-site/funflow.js:30:21)
        at next (/home/imaman/workspace/green-site/funflow.js:24:22)
        at applyAt (/home/imaman/workspace/green-site/funflow.js:30:21)
        at next (/home/imaman/workspace/green-site/funflow.js:24:22)

    Finished in 1.628 seconds
    36 tests, 77 assertions, 2 failures, 0 skipped

That is: two failing assertions at the same spec. The message emitted by
the second failing assertion is quite opaque: "Expected '' to be
undefined.". OTOH, the message from the first one is clearer and
almost immediately actionable: "Expected null to equal
'mostRecentRelease() failed'". Thus, we change the specs to get rid of
the second failure (when the first one fails) to get a better
signal-to-noise ratio.